### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by RedSevenMale** [hanxu317317/city_pickers#156]
/city_pickers-1.2.1/lib/src/cities_selector/cities_selector.dart:116:48: Error: The getter 'accentColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('/D:/flutter/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'accentColor'.
      textColor: widget.itemFontColor ?? theme.accentColor,
                                               ^^^^^^^^^^^
                                               
                                               
                                               
![image](https://user-images.githubusercontent.com/39144187/227196461-523126b3-37dc-40c4-aac4-c93ef759ca7c.png)

**Comment by ipcjs** [comment]
你Flutter的版本是？

**Comment by RedSevenMale** [comment]
> 
Flutter 3.9.0-15.0.pre.22 • channel main • https://github.com/flutter/flutter.git
Framework • revision 250a6c2942 (2 hours ago) • 2023-03-23 05:47:28 -0400
Engine • revision 59acb53620
Tools • Dart 3.0.0 (build 3.0.0-358.0.dev) • DevTools 2.22.2
切换beta、stable都报错

**Comment by ipcjs** [comment]
你这有点超前了（
stable频道应该是没有问题的

**Comment by ltq918** [comment]
我也在 city_pickers-1.2.1 中遇到了这个问题
可以修改 /Pub/Cache/hosted/pub.dev/city_pickers-1.2.1/lib/cities_selector.dart
117 行   theme.colorScheme.secondary, //theme.accentColor,

**Comment by kj415j45** [comment]
Fixed by #160.

Consider use git version before new release.
```yaml
dependencies:
  city_pickers: # FIXME: Use latest version instead after the commit release.
    git:
      url: https://github.com/hanxu317317/city_pickers
      ref: 8a702e52d52e17df9995353748b3dfe088f27de9
```
