### ISSUE TITLE
Support for flutter 3.10.0?

### ISSUE THREAD

**Issue by wozyao** [hanxu317317/city_pickers#162]

**Comment by kj415j45** [comment]
Fixed by #160.

Consider use git version before new release.
```yaml
dependencies:
  city_pickers: # FIXME: Use latest version instead after the commit release.
    git:
      url: https://github.com/hanxu317317/city_pickers
      ref: 8a702e52d52e17df9995353748b3dfe088f27de9
```
